
package ru.iflex.esb.informing.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.6
 * 2021-09-23T12:32:49.610+03:00
 * Generated source version: 3.3.6
 */

@WebFault(name = "InformingFault", targetNamespace = "http://informing.nsc.ru/")
public class InformingFault_Exception extends Exception {

    private InformingFault informingFault;

    public InformingFault_Exception() {
        super();
    }

    public InformingFault_Exception(String message) {
        super(message);
    }

    public InformingFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InformingFault_Exception(String message, InformingFault informingFault) {
        super(message);
        this.informingFault = informingFault;
    }

    public InformingFault_Exception(String message, InformingFault informingFault, Throwable cause) {
        super(message, cause);
        this.informingFault = informingFault;
    }

    public InformingFault getFaultInfo() {
        return this.informingFault;
    }
}
